#! /bin/sh
### BEGIN INIT INFO
# Provides:          videosdisabling
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Switches off video output to save energy
### END INIT INFO

PATH=/sbin:/bin

. /lib/lsb/init-functions

do_start () {
    /opt/vc/bin/tvservice --off
}

do_stop () {
    /opt/vc/bin/tvservice --preferred
}

do_status() {
    /opt/vc/bin/tvservice --status
}

case "$1" in
  start)
    do_start
    ;;
  stop)
    do_stop
    ;;
  status)
    # No-op
    ;;
  restart|reload|force-reload)
    echo "Error: argument '$1' not supported" >&2
    exit 3
    ;;
  *)
    echo "Usage: $0 start|stop" >&2
    exit 3
    ;;
esac
