- name: fail2ban reload
  become: true
  service:
    name: fail2ban
    state: restarted

- name: syslog-ng reload
  become: true
  service:
    name: syslog-ng
    state: restarted

- name: rsyslog reload
  become: true
  service:
    name: rsyslog
    state: restarted
