- name: clone nextcloud sources
  git:
    repo: https://github.com/nextcloud/server.git
    dest: ~/public_html/owncloud
    update: no

- name: create apps2 directory
  file:
    path: ~/public_html/owncloud/apps2
    state: directory

- name: clone app sources
  git:
    repo: "https://github.com/nextcloud/{{ item }}.git"
    dest: "~/public_html/owncloud/apps2/{{ item }}"
    update: no
  with_items:
    - calendar
    - contacts
    - deck
    - files_rightclick
    - mail
    - photos
    #- previewgenerator
    - ransomware_protection
    - tasks
    - text
    - viewer
