- name: install cups
  become: true
  apt:
    name: cups
    state: present

- name: install LPR driver
  become: true
  apt:
    deb: http://download.brother.com/welcome/dlf005881/hl2240dlpr-2.1.1-1.i386.deb
    state: present

- name: install cups wrapper
  become: true
  apt:
    deb: http://download.brother.com/welcome/dlf005883/cupswrapperHL2240D-2.0.4-2.i386.deb
    state: present
