- hosts: cam
  roles:
    - common
    - cam
  tags:
    - headless

- hosts: cuddles
  roles:
    - common
    - mail
    - web
    - irc
    - dns
    - database
    - voip
    - backup
    - tor
    - xmpp
    - printer

- hosts: edf
  roles:
    - common
  tags:
    - headless

- hosts: handy
  roles:
    - common

- hosts: kimsufi
  roles:
    - common
    - reverse_proxy
    - seedbox
    - backup_dns
    - iodine
    - backup_mx

- hosts: tv-ch1 tv-ch2 tv-salon
  roles:
    - tv

- hosts: vmc
  roles:
    - common
  tags:
    - headless
