- hosts: cam
  roles:
    - common
    - cam

- hosts: cuddles
  roles:
    - common
    - web
    - irc
    - dns

- hosts: edf
  roles:
    - common

- hosts: handy
  roles:
    - common

- hosts: kimsufi
  roles:
    - common
    - reverse_proxy
    - seedbox

- hosts: tv-ch1 tv-ch2 tv-salon
  roles:
    - tv

- hosts: vmc
  roles:
    - common
