- hosts: cam
  roles:
    - common

- hosts: cuddles
  roles:
    - common
    - web

- hosts: edf
  roles:
    - common

- hosts: handy
  roles:
    - common

- hosts: kimsufi
  roles:
    - common
    - reverse_proxy
    - seedbox

- hosts: vmc
  roles:
    - common
