- hosts: cuddles
  roles:
    - crypt
    - common
    - mail
    - web
    - database
    - backup
    - printer
    - cloud
    - nfs
    - forge
    - pihole

- hosts: handy
  roles:
    - common

- hosts: tv-ch1 tv-salon
  roles:
    - tv
