- hosts: cam
  roles:
    - common
    - cam
  tags:
    - headless

- hosts: cuddles
  roles:
    - crypt
    - common
    - mail
    - web
    - irc
    - dns
    - database
    - backup
    - tor
    - xmpp
    - printer
    - domotic/provisioning/mqtt
    - message_broker
    - git
    - cloud
    - nfs
    - forge

- hosts: edf
  roles:
    - common
    - domotic/provisioning/teleinfo
    - domotic/provisioning/weather
  tags:
    - headless
    - wifi

- hosts: handy
  roles:
    - common

- hosts: kimsufi
  roles:
    - common
    - reverse_proxy
    - seedbox
    - backup_dns
    - iodine
    - backup_mx

- hosts: tv-ch1 tv-ch2 tv-salon
  roles:
    - tv

- hosts: vmc
  roles:
    - common
    - domotic/provisioning/vmc
    - vmc
  tags:
    - headless
    - wifi
