- hosts: cuddles
  roles:
    - crypt
    - common
    - mail
    - web
    - irc
    - dns
    - database
    - backup
    - xmpp
    - printer
    - domotic/provisioning/mqtt
    - message_broker
    - git
    - cloud
    - nfs
    - forge
    - cfp
    - syncserver

- hosts: handy
  roles:
    - common

- hosts: tv-ch1 tv-ch2 tv-salon
  roles:
    - tv
