- name: install ngircd
  become: true
  apt:
    name: ngircd
    state: present

- name: copy ngircd configuration
  become: true
  template:
    src: irc/files/ngircd.conf
    group: irc
    dest: /etc/ngircd/
  notify: ngircd restart

- name: copy ngircd motd
  become: true
  copy:
    src: ngircd.motd
    group: irc
    dest: /etc/ngircd/
  notify: ngircd restart
