- name: install postfix
  become: true
  apt:
    name: postfix
    state: present

- name: copy postfix configuration
  become: true
  copy:
    src: main.cf
    dest: /etc/postfix/
  notify: postfix reload
