- name: add rspamd repository key
  become: true
  apt_key:
    url: https://rspamd.com/apt-stable/gpg.key

- name: add rspamd apt repository
  become: true
  apt_repository:
    repo: 'deb [arch=amd64] https://rspamd.com/apt-stable/ {{ debian_version }} main'
    state: present
    filename: rspamd

- name: install rspamd
  become: true
  package:
    name: rspamd
    state: present
    update_cache: yes

- name: start rspamd service
  become: true
  service:
    name: rspamd
    state: started
    enabled: yes
