- set_fact:
    bind_pkg: bind9
    bind_service: bind9
  when: ansible_distribution == "Debian"

- set_fact:
    bind_pkg: bind
    bind_service: named
  when: ansible_distribution == "Arch Linux"

- name: install "{{ bind_pkg }}"
  become: true
  package:
    name: "{{ bind_pkg }}"
    state: present
  when: ansible_distribution == "Debian"

- name: copy bind master configuration
  become: true
  copy:
    src: dns/files/named.conf
    dest: /etc/
  notify: bind reload
  when: ansible_distribution == "Arch Linux"

- name: copy bind configuration
  become: true
  copy:
    src: "{{ item }}"
    dest: /etc/bind/
  with_items:
    - named.conf.local
    - named.conf.options
  notify: bind reload

- name: copy zones configuration
  become: true
  copy:
    src: "{{ item }}"
    dest: /var/cache/bind/
  with_fileglob:
    - dns/files/zones/*
  notify: bind reload

- name: start "{{ bind_service }}" service
  service:
    name: "{{ bind_service }}"
    state: started
    enabled: yes
