- set_fact:
    pg_stat_tmp: "/var/lib/postgresql/pg_stat_tmp"

- name: creates {{ pg_stat_tmp }}
  become: true
  file:
    path: "{{ pg_stat_tmp }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0700

- name: creates pg_stat_tmp mount point
  become: true
  mount:
    path: "{{ pg_stat_tmp }}"
    src: tmpfs
    fstype: tmpfs
    opts: size=2g,uid=postgres,gid=postgres,mode=0700
    state: mounted

- name: copy postgresql configuration
  become: true
  copy:
    src: "{{ item }}"
    dest: "/etc/postgresql/{{ postgres_version }}/main/"
    owner: postgres
    group: postgres
  with_fileglob:
    - postgresql/*
  notify: postgresql reload

- file:
    path: "/etc/postgresql/{{ postgres_version }}/main/{{ item }}"
    mode: 0640
  become: true
  with_items:
    - pg_hba.conf
    - pg_ident.conf
