- name: copy postgresql configuration
  become: true
  copy:
    src: "{{ item }}"
    dest: "/etc/postgresql/{{ postgres_version }}/main/"
    owner: postgres
    group: postgres
  with_fileglob:
    - postgresql/*
  notify: postgresql reload

- file:
    path: "/etc/postgresql/{{ postgres_version }}/main/{{ item }}"
    mode: 0640
  become: true
  with_items:
    - pg_hba.conf
    - pg_ident.conf
