- name: install nginx
  become: true
  package:
    name: nginx
    state: present

- name: remove default vhost
  become: true
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: remove default ssl configuration
  become: true
  lineinfile:
    dest: /etc/nginx/nginx.conf
    regexp: "ssl_"
    state: "absent"

- name: generate dhparam
  become: true
  command: openssl dhparam -out /etc/ssl/private/dh4096.pem 4096
  args:
    creates: /etc/ssl/private/dh4096.pem

- name: copy nginx TLS configuration
  become: true
  copy:
    src: common/files/tls.conf
    dest: /etc/nginx/conf.d/
  notify: nginx reload

- name: copy vhosts
  become: true
  copy:
    src: "{{ item }}"
    dest: /etc/nginx/sites-enabled/
  with_fileglob:
    - vhost/*
  notify: nginx reload
