- stat:
    path: /etc/pam.d/cron
  register: pam_cron

- name: reduce pam log
  become: true
  lineinfile:
    dest: /etc/pam.d/cron
    regexp: '^(@include common-session-noninteractive)'
    line: '#\1'
    backrefs: yes
  when: pam_cron.stat.exists == True
