- name: create git user
  become: true
  user:
    name: git
    state: present
    groups: [www-data, sanpi]
    append: yes

- name: install git & make
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - make
    - git

- include_tasks: forge/tasks/bower.yml

- name: install pelican
  become: true
  package:
    name: pelican
    state: present
