- name: install gnusocial service
  become: true
  template:
    src: files/gnusocial.service.j2
    dest: /etc/systemd/system/gnusocial

- name: enable gnusocial service
  become: true
  service:
    name: gnusocial
    state: started
    enabled: yes

- name: restart gnusocial service each night
  become: true
  cron:
    hour: 3
    minute: 0
    job: "systemctl restart gnusocial"
    user: root
    cron_file: gnusocial
