- include: common/tasks/nginx.yml

- name: copy nginx CSP configuration
  become: true
  copy:
    src: csp.conf
    dest: /etc/nginx/conf.d/
  notify: nginx reload

- name: copy nginx X-Content-Type-Options configuration
  become: true
  copy:
    src: cto.conf
    dest: /etc/nginx/conf.d/
  notify: nginx reload

- name: copy nginx X-Frame-Options configuration
  become: true
  copy:
    src: xfo.conf
    dest: /etc/nginx/conf.d/
  notify: nginx reload
