- name: instal php
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - php-cli
    - php-common
    - php-curl
    - php-fpm
    - php-gd
    - php-intl
    - php-json
    - php-mbstring
    - php-pgsql
    - php-readline
    - php-sqlite3
    - php-xml
    - php-zip
  notify: php-fpm reload

- name: copy php configuration
  become: true
  copy:
    src: php.ini
    dest: /etc/php/mods-available/custom.ini
  notify: php-fpm reload

- name: enable php configuration
  become: true
  file:
    src: /etc/php/mods-available/custom.ini
    dest: "{{ item }}/99-custom.ini"
    state: link
  with_items:
    - "/etc/php/{{ php_version }}/cli/conf.d"
    - "/etc/php/{{ php_version }}/fpm/conf.d"
  notify: php-fpm reload

- name: create php-fpm directory
  become: true
  file:
    path: /run/php/php-fpm
    state: directory

- name: copy php fpm configuration
  become: true
  copy:
    src: "{{ item }}"
    dest: "/etc/php/{{ php_version }}/fpm/pool.d"
  with_fileglob:
    - php-fpm/*
  notify: php-fpm reload
