- set_fact:
    bind_pkg: bind9
    bind_service: bind9
  when: ansible_distribution == "Debian"

- set_fact:
    bind_pkg: bind
    bind_service: named
  when: ansible_distribution == "Arch Linux"

- name: bind reload
  become: true
  service:
    name: "{{ bind_pkg }}"
    state: reloaded

- name: dnssec sign
  become: true
  command: for zone in $(ls /var/cache/bind/*.zone); do dnssec-signzone -A -3 "$(date | sha1sum | cut -b 1-16)" -N increment -o $(basename $zone | sed 's/.zone//') -t "$zone"; done
  args:
    chdir: /etc/bind/dnssec/
