- name: install ruby dependencies
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - ruby
    - ruby-dev
    - libpq-dev

- name: update rake
  become: true
  gem:
    name: rake
    state: present
