- name: install certbot
  become: true
  package:
    name: certbot
    state: present

- name: install git
  become: true
  package:
    name: git
    state: present

- name: clone deploy scripts
  git:
    repo: https://github.com/sanpii/deploy.git
    dest: "~/deploy"

- name: copy letsencrypt configuration
  copy:
    src: letsencrypt.sh
    dest: "~/deploy/src/config/"

- name: install cron
  become: true
  cron:
    name: "letsencrypt"
    job: "/home/sanpi/deploy/src/ssl"
    state: "present"
    weekday: 7
    hour: 23
    minute: 0
    cron_file: letsencrypt
    user: root

- name: create letsencrypt webroot
  file:
    dest: /tmp/letsencrypt/public_html/
    state: directory

- name: remove default certbot cron task
  become: true
  file:
    dest: /etc/cron.d/certbot
    state: absent
