- include: common/tasks/nginx.yml

- name: create proxy cache directory
  become: true
  file:
    path: /var/cache/nginx
    owner: www-data
    group: www-data
    state: directory
  notify: nginx reload

- name: copy proxy configuration
  become: true
  copy:
    src: proxy.conf
    dest: /etc/nginx/conf.d/
  notify: nginx reload
