- name: install motion
  become: true
  apt:
    name: motion
    state: present

# https://github.com/dozencrows/motion/tree/mmal-test
- name: install motion-mmal
  copy:
    src: motion
    dest: ~

- name: copy motion configuration
  become: true
  copy:
    src: motion.conf
    dest: /etc/motion/

- name: copy motion script
  copy:
    src: motion.sh
    dest: ~

- name: launch motion at startup
  become: true
  lineinfile:
    dest: /etc/rc.local
    line: 'sudo -u pi /home/pi/motion.sh&'
    insertbefore: 'exit 0'
