- import_tasks: ca.yml
- import_tasks: cron.yml
- import_tasks: avahi.yml
- import_tasks: ferm.yml
- import_tasks: smartctl.yml
- import_tasks: fail2ban.yml
- import_tasks: mail.yml
- import_tasks: pam.yml
- import_tasks: cron-apt.yml
  when: ansible_os_family == "Debian"
- import_tasks: video-off.yml
  tags:
    - headless
- import_tasks: wifi.yml
  tags:
    - wifi
