- name: install mysql server
  become: true
  package:
    name: mariadb-server
    state: present

- name: copy mysql configuration
  become: true
  copy:
    src: mysql.cnf
    dest: /etc/mysql/conf.d/custom.cnf
  notify: mysql reload
