- name: install postgresql-server-dev
  become: true
  package:
    name: postgresql-server-dev-9.6
    state: present

- name: download pg_qualstats sources
  unarchive:
    src: https://github.com/dalibo/pg_qualstats/archive/1.0.2.tar.gz
    dest: /tmp
    remote_src: true

- name: compiling pg_qualstats
  make:
    chdir: /tmp/pg_qualstats-1.0.2/

- name: installing pg_qualstats
  become: true
  make:
    chdir: /tmp/pg_qualstats-1.0.2/
    target: install

- name: remove sources
  file:
    path: /tmp/pg_qualstats-1.0.2/
    state: absent
