- name: install postgresql server
  become: true
  package:
    name: postgresql
    state: present

- name: copy postgresql configuration
  become: true
  copy:
    src: "{{ item }}"
    dest: /etc/postgresql/9.6/main/
    owner: postgres
    group: postgres
  with_fileglob:
    - postgresql/*
  notify: postgresql reload

- file:
    path: "/etc/postgresql/9.6/main/{{ item }}"
    mode: 0640
  become: true
  with_items:
    - pg_hba.conf
    - pg_ident.conf
