- name: add postgresql repository key
  become: true
  apt_key:
    url: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc'

- name: add postgresql apt repository
  become: true
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main'
    state: present
    filename: postgresql

- name: install postgresql server
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql
    - postgresql-contrib-9.6

- name: copy postgresql configuration
  become: true
  copy:
    src: "{{ item }}"
    dest: /etc/postgresql/9.6/main/
    owner: postgres
    group: postgres
  with_fileglob:
    - postgresql/*
  notify: postgresql reload

- file:
    path: "/etc/postgresql/9.6/main/{{ item }}"
    mode: 0640
  become: true
  with_items:
    - pg_hba.conf
    - pg_ident.conf

- include: powa.yml
