- name: install powa
  become: true
  package:
    name: postgresql-9.6-powa
    state: present

- stat:
    path: /usr/lib/postgresql/9.6/lib/pg_qualstats.so
  register: pg_qualstats

- include: pg_qualstats.yml
  when: pg_qualstats.stat.exists == False

- stat:
    path: /usr/lib/postgresql/9.6/lib/pg_stat_kcache.so
  register: pg_stat_kcache

- include: pg_stat_kcache.yml
  when: pg_stat_kcache.stat.exists == False

- stat:
    path: /usr/lib/postgresql/9.6/lib/hypopg.so
  register: hypopg

- include: hypopg.yml
  when: hypopg.stat.exists == False

- name: create powa user
  become: true
  become_user: postgres
  postgresql_user:
    name: powa
    role_attr_flags: SUPERUSER,LOGIN
    password: "{{ powa_password }}"

- name: create powa database
  become: true
  become_user: postgres
  postgresql_db:
    name: powa
    owner: powa

- name: enable extensions for powa
  become: true
  become_user: postgres
  postgresql_ext:
    name: "{{ item }}"
    db: powa
  with_items:
    - pg_stat_statements
    - btree_gist
    - powa
    - pg_qualstats
    - pg_stat_kcache
    - hypopg

- name: install powa-web
  become: true
  pip:
    name: powa-web

- name: copy powa-web configuration
  become: true
  template:
    src: files/powa-web.conf
    dest: /etc

- name: copy powa-web uwsgi configuration
  become: true
  copy:
    src: powa.ini
    dest: /etc/uwsgi/apps-enabled
  notify: uwsgi reload

- name: copy nginx configuration
  become: true
  copy:
    src: powa.homecomputing.fr
    dest: /etc/nginx/sites-enabled/
  notify: nginx reload
